### PR TITLE
Fix CurrentSelection for multiple post types

### LINKED ISSUE #86: CurrentSelection component doesn't show selected posts for multiple post types
When the `postType` prop of `PostSelectButton` is array of multiple post types, `CurrentSelection` doesn't show the selected posts. This happens because the `CurrentSelection` components uses `getEntityRecords()`, which doesn't allow multiple post types to be queried at once.

### PR DESCRIPTION
**Pull request by gonzomir**
Trying to fix #86 by registering the custom post select endpoint with `wp.data` and then using it with `getEntityRecords()`. I think this approach can be used for browsing posts too.

### CODE REVIEW

**Comment by kadamwhite** [comment]
This looks promising but I wonder if we should try to migrate to the core wp/v2/search endpoint, which this plugin https://github.com/humanmade/rest-api-search-by-id makes possible by adding support for "include" on the search endpoint? I'm hoping to add that include support in core, so if we are able over time to migrate away from the custom endpoint we can sunset a lot of code in this repo. 

If that's out of scope for now, totally understand

**Review by kadamwhite — APPROVED** [review]
@gonzomir This worked when I tested it out today

File: js/current-selection/index.js [hunk 1]
```diff
@@ -2,14 +2,26 @@ import wp from 'wp';
...
+] );
 
 export default withSelect( ( select, ownProps ) => {
 	const { getEntityRecords } = select( 'core' );
 	const { postIds, postType } = ownProps;
-	const posts = getEntityRecords( 'postType', postType, {
+	const postTypes = Array.isArray( postType ) ? postType : [ postType ];
+	const posts = getEntityRecords( 'hm-gb-tools/v1', 'post-select', {
 		include: postIds,
+		per_page: postIds.length,
```
Comment (kadamwhite) [inline js/current-selection/index.js:21]: This doesn't really benefit us given the `include`, though I grant it does not hurt
