### PR TITLE
Fix frame buttons alignment

### LINKED ISSUE #16: Frame buttons alignment
On Firefox, the buttons are correctly right-aligned, but on Chrome, they're left-aligned.

### PR DESCRIPTION
**Pull request by kucrut**
Fixes #16.

### CODE REVIEW

File: js/components/post-select/modal.js [hunk 1]
```diff
@@ -103,23 +103,21 @@ class PostSelectModal extends React.Component {
 				</div>
 				<div className="media-frame-toolbar">
 					<div className="media-toolbar">
+						<Button
+							isPrimary={true}
+							isLarge={true}
```
Comment (rmccue) [inline js/components/post-select/modal.js]: These should usually be alphabetised and with spaces inside the `{}`, but matches surrounding style.

Comment (mattheu) [reply js/components/post-select/modal.js]: Regarding the spaces inside the `{}` - The HM eslint rules don't seem to have an opinion either way on this one. I think I'd prefer the spaces - but would be good to make sure this is enforced/fixed by ESLint. I'm happy to merge for now because - as you say - matches surrounding style.

Comment (mattheu) [reply js/components/post-select/modal.js]: Added a PR here: https://github.com/humanmade/coding-standards/pull/38
